#!/bin/bash
# File protection hook - validates file operations on sensitive paths
# Exit codes: 0 = allow, 2 = block

# Read JSON input from stdin
INPUT=$(cat)

# Extract file path from tool_input
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.path // empty')

# If no file path, allow
if [[ -z "$FILE_PATH" ]]; then
    exit 0
fi

# =============================================================================
# BLOCKED FILES - Never allow modification
# =============================================================================

# Environment files with secrets
if [[ "$FILE_PATH" =~ \.env($|\.) ]] && [[ ! "$FILE_PATH" =~ \.env\.example ]]; then
    echo "BLOCKED: Cannot modify .env files - edit manually for security" >&2
    exit 2
fi

# AWS credentials
if [[ "$FILE_PATH" =~ \.aws/credentials ]]; then
    echo "BLOCKED: Cannot modify AWS credentials" >&2
    exit 2
fi

# SSH keys
if [[ "$FILE_PATH" =~ \.ssh/id_ ]]; then
    echo "BLOCKED: Cannot modify SSH keys" >&2
    exit 2
fi

# GPG keys
if [[ "$FILE_PATH" =~ \.gnupg/ ]]; then
    echo "BLOCKED: Cannot modify GPG directory" >&2
    exit 2
fi

# Secrets directory
if [[ "$FILE_PATH" =~ /secrets/ ]]; then
    echo "BLOCKED: Cannot modify files in secrets directory" >&2
    exit 2
fi

# =============================================================================
# WARNING FILES - Allow but warn
# =============================================================================

# Package lock files (regenerated by npm)
if [[ "$FILE_PATH" =~ package-lock\.json ]] || [[ "$FILE_PATH" =~ yarn\.lock ]] || [[ "$FILE_PATH" =~ pnpm-lock\.yaml ]]; then
    echo "WARNING: Modifying lock file - usually auto-generated by package manager" >&2
fi

# Git internals
if [[ "$FILE_PATH" =~ \.git/ ]]; then
    echo "WARNING: Modifying git internals - this could corrupt the repository" >&2
fi

# Build output directories
if [[ "$FILE_PATH" =~ (node_modules|\.next|dist|build)/ ]]; then
    echo "WARNING: Modifying build output directory - usually auto-generated" >&2
fi

# Configuration files that affect security
if [[ "$FILE_PATH" =~ (next\.config|vite\.config|webpack\.config|tsconfig) ]]; then
    echo "NOTE: Modifying build configuration - ensure security settings are preserved" >&2
fi

# =============================================================================
# SAFE - Allow the operation
# =============================================================================

exit 0
