#!/bin/bash
# Claude Code Configuration Audit
# ──────────────────────────────────────────────────────────────────────────
# Deterministic check of ~/.claude/ against known schema violations and
# drift patterns. Runs quarterly via launchd (see
# scripts/com.user.claude-audit.plist.template — rename + adapt for your
# machine before loading with `launchctl load`).
# Manual run: bash ~/.claude/scripts/audit-config.sh
#
# Output: ~/.claude/audit-reports/audit-YYYY-MM-DD.md
# Exit codes:
#   0 — no issues found (all clean)
#   1 — issues found (report has CRITICAL / WARN findings)
#   2 — script error (couldn't run)
#
# Audit basis: official Claude Code docs at https://code.claude.com/docs/en/
# Update this script when new drift patterns are discovered.
set -uo pipefail

CLAUDE_DIR="$HOME/.claude"
REPORT_DIR="$CLAUDE_DIR/audit-reports"
DATE=$(date '+%Y-%m-%d')
REPORT="$REPORT_DIR/audit-${DATE}.md"
mkdir -p "$REPORT_DIR"

# Use plain text counters since associative arrays don't survive subshells well
CRITICAL_COUNT=0
WARN_COUNT=0

# Buffer findings; we tally CRITICAL/WARN by parsing this at the end so the
# counters survive subshells (the previous version under-reported because
# heredoc/while pipelines run in a subshell that can't mutate parent state).
FINDINGS_TMP=$(mktemp)

emit_critical() {
    printf '🔴 **CRITICAL** — %s\n\n' "$1" >> "$FINDINGS_TMP"
}
emit_warn() {
    printf '🟡 **WARN** — %s\n\n' "$1" >> "$FINDINGS_TMP"
}

# ============================================================================
# Header
# ============================================================================
cat > "$REPORT" <<EOF
# Claude Code Config Audit — $DATE

Auto-generated by \`~/.claude/scripts/audit-config.sh\`.
Runs quarterly via launchd. Manual run: \`bash ~/.claude/scripts/audit-config.sh\`.

## Findings

EOF

# ============================================================================
# settings.json checks
# ============================================================================
SETTINGS="$CLAUDE_DIR/settings.json"
if [[ -f "$SETTINGS" ]]; then

    # Invalid top-level fields
    for bad_field in theme agentPushNotifEnabled skipAutoPermissionPrompt observations hangoutDocsAt autoCompactThreshold autoCompactPctOverride agentMatching authRefresh fontFamily; do
        if jq -e --arg k "$bad_field" 'has($k)' "$SETTINGS" >/dev/null 2>&1; then
            emit_critical "settings.json has invalid field \`$bad_field\` (not in official schema)"
        fi
    done

    # Deprecated fields
    for dep_field in voiceEnabled includeCoAuthoredBy; do
        if jq -e --arg k "$dep_field" 'has($k)' "$SETTINGS" >/dev/null 2>&1; then
            emit_critical "settings.json has deprecated field \`$dep_field\` — migrate per docs"
        fi
    done

    # Custom multi-key blocks that look like fields but aren't in schema
    if jq -e '.agents' "$SETTINGS" >/dev/null 2>&1; then
        # The valid field is singular "agent" (string). "agents" (object) is custom.
        if jq -e '.agents | type == "object"' "$SETTINGS" >/dev/null 2>&1; then
            emit_critical "settings.json has custom \`agents\` object (only singular \`agent\` string is valid)"
        fi
    fi

    # Permission rule syntax checks
    if jq -r '.permissions.deny[]?' "$SETTINGS" 2>/dev/null | grep -qE 'Bash\([^)]*\|[^)]*\)'; then
        emit_critical "settings.json deny rule uses pipe-alternation inside Bash() — split into separate entries"
    fi

    if jq -r '.permissions.allow[]?' "$SETTINGS" 2>/dev/null | grep -qE '^Task(\(|$)'; then
        emit_critical "settings.json allow has \`Task(*)\` or \`Task\` — Task is not a real tool, Agent is"
    fi

    # Hook double-registration: postbash-failure-recovery.sh should only be in PostToolUseFailure
    if jq -r '.hooks.PostToolUse[]?.hooks[]?.command' "$SETTINGS" 2>/dev/null | grep -q 'postbash-failure-recovery.sh'; then
        emit_warn "postbash-failure-recovery.sh registered under PostToolUse (success-only event) — only PostToolUseFailure fires it"
    fi

    # Stop / SubagentStop matcher "*" (not in docs)
    for ev in Stop SubagentStop; do
        if jq -r --arg ev "$ev" '.hooks[$ev][]?.matcher // empty' "$SETTINGS" 2>/dev/null | grep -q '^\*$'; then
            emit_warn "settings.json hooks.$ev uses matcher \"*\" — docs say no matcher for $ev"
        fi
    done

else
    emit_critical "settings.json not found at $SETTINGS"
fi

# ============================================================================
# Agents checks
# ============================================================================
INVALID_TOOLS_REGEX='TaskCreate|TaskUpdate|TaskList|TaskGet|ExitPlanMode|NotebookEdit'
NON_SCHEMA_FIELDS='^(permissionMode|skills|hooks):'
STALE_MODEL_REGEX='claude-(opus|sonnet|haiku)-(3|4-1)-[0-9]{8}|claude-haiku-4-2025|claude-opus-4-1-2025'

for f in "$CLAUDE_DIR"/agents/*.md; do
    [[ -f "$f" ]] || continue
    bn=$(basename "$f")

    # Extract frontmatter (between first two --- lines)
    fm=$(awk '/^---$/{c++; next} c==1' "$f")

    # Invalid tool names in tools list
    if echo "$fm" | grep -qE "^\s*-\s*($INVALID_TOOLS_REGEX)\s*$"; then
        invalid=$(echo "$fm" | grep -oE "($INVALID_TOOLS_REGEX)" | sort -u | tr '\n' ' ')
        emit_critical "agents/$bn lists invalid tool names: $invalid"
    fi

    # Non-schema top-level fields
    bad=$(echo "$fm" | grep -E "$NON_SCHEMA_FIELDS" | sed 's/:.*//' | sort -u | tr '\n' ' ')
    if [[ -n "$bad" ]]; then
        emit_warn "agents/$bn has non-schema frontmatter fields: $bad"
    fi

    # Stale model IDs
    if echo "$fm" | grep -qE "^\s*model:.*($STALE_MODEL_REGEX)"; then
        stale=$(echo "$fm" | grep -E "^\s*model:" | sed 's/.*model:[[:space:]]*//' | head -1)
        emit_critical "agents/$bn uses stale model ID: $stale (use shortname haiku/sonnet/opus)"
    fi

    # Missing required fields
    if ! echo "$fm" | grep -qE "^name:"; then
        emit_critical "agents/$bn missing required \`name\` field"
    fi
    if ! echo "$fm" | grep -qE "^description:"; then
        emit_warn "agents/$bn missing \`description\` field"
    fi
done

# ============================================================================
# Commands / Skills checks (merged per docs)
# ============================================================================
# Bundled command names — collisions shadow built-in functionality
BUNDLED_COMMANDS="review|init|security-review|code-review|compact|clear|help|model|fast|verify|run|loop|schedule"

for f in "$CLAUDE_DIR"/commands/*.md; do
    [[ -f "$f" ]] || continue
    bn=$(basename "$f" .md)

    if echo "$bn" | grep -qE "^($BUNDLED_COMMANDS)$"; then
        emit_critical "commands/$bn.md shadows bundled /$bn — rename to avoid collision"
    fi

    fm=$(awk '/^---$/{c++; next} c==1' "$f")
    if echo "$fm" | grep -qE "^\s*model:.*($STALE_MODEL_REGEX)"; then
        stale=$(echo "$fm" | grep -E "^\s*model:" | sed 's/.*model:[[:space:]]*//' | head -1)
        emit_critical "commands/$bn.md uses stale model ID: $stale"
    fi
done

# command-contract-lint.sh (IMP-089 closed-loop wiring, 2026-07-15): the
# controller-contract marker/frontmatter/preamble/deny-ref/agent-existence
# checks live in their own dedicated linter, not duplicated here — invoke it
# once and fold its per-line failures into WARN findings on this report.
CONTRACT_LINT="$CLAUDE_DIR/scripts/command-contract-lint.sh"
if [[ -f "$CONTRACT_LINT" ]]; then
    contract_out=$(bash "$CONTRACT_LINT" "$CLAUDE_DIR/commands" 2>&1)
    if [[ $? -ne 0 ]]; then
        while IFS= read -r line; do
            [[ "$line" == \[*\]* ]] || continue
            emit_warn "command-contract-lint: $line"
        done <<< "$contract_out"
    fi
else
    emit_warn "command-contract-lint.sh not found at $CONTRACT_LINT — controller-contract checks skipped this run"
fi

# Skills
for f in "$CLAUDE_DIR"/skills/*/SKILL.md; do
    [[ -f "$f" ]] || continue
    dir=$(basename "$(dirname "$f")")
    fm=$(awk '/^---$/{c++; next} c==1' "$f")

    # Stale model
    if echo "$fm" | grep -qE "^\s*model:.*($STALE_MODEL_REGEX)"; then
        stale=$(echo "$fm" | grep -E "^\s*model:" | sed 's/.*model:[[:space:]]*//' | head -1)
        emit_critical "skills/$dir/SKILL.md uses stale model ID: $stale"
    fi

    # Legacy fields (not in current Claude Code skill schema)
    for legacy in "^triggers:" "^category:" "^mode:" "^context: forked$"; do
        if echo "$fm" | grep -qE "$legacy"; then
            emit_warn "skills/$dir/SKILL.md has legacy field matching \`$legacy\`"
        fi
    done

    # `tools:` instead of `allowed-tools:`
    if echo "$fm" | grep -qE "^tools:" && ! echo "$fm" | grep -qE "^allowed-tools:"; then
        emit_warn "skills/$dir/SKILL.md uses \`tools:\` (should be \`allowed-tools:\`)"
    fi

    # name regex check
    name=$(echo "$fm" | grep -E "^name:" | head -1 | sed 's/^name:[[:space:]]*//')
    if [[ -n "$name" ]] && ! echo "$name" | grep -qE '^[a-z0-9-]+$'; then
        emit_warn "skills/$dir/SKILL.md name \"$name\" violates ^[a-z0-9-]+\$ regex"
    fi
done

# ============================================================================
# Hooks checks — silently-broken pattern
# ============================================================================
# Pattern: script uses $1 without stdin fallback → receives literal unexpanded
# "$file_path" / "$tool_name" string from settings.json and exits silently.
for f in "$CLAUDE_DIR"/hooks/*.sh; do
    [[ -f "$f" ]] || continue
    bn=$(basename "$f")

    # Look for "$1" usage early in the file
    uses_positional=$(head -30 "$f" | grep -cE '="\$1"|=\$1\b' || true)
    reads_stdin=$(grep -cE 'INPUT=\$\(cat\)|read.*INPUT' "$f" || true)

    if [[ "$uses_positional" -gt 0 ]] && [[ "$reads_stdin" -eq 0 ]]; then
        emit_warn "hooks/$bn uses \$1 without stdin-cat fallback (silent-broken pattern; \$tool_name/\$file_path are not substituted by Claude Code)"
    fi
done

# Bogus var substitutions in settings.json hook commands
if [[ -f "$SETTINGS" ]]; then
    bogus=$(jq -r '.. | objects | select(.command?) | .command' "$SETTINGS" 2>/dev/null | grep -oE '\$(tool_name|tool_args|tool_input|file_path)' | sort -u | tr '\n' ' ')
    if [[ -n "$bogus" ]]; then
        emit_critical "settings.json hook commands reference unsupported vars: $bogus (Claude Code only substitutes \${CLAUDE_PROJECT_DIR}, \${CLAUDE_PLUGIN_ROOT}, etc.)"
    fi
fi

# ============================================================================
# Tally + write findings
# ============================================================================
CRITICAL_COUNT=$(grep -c '^🔴 \*\*CRITICAL\*\*' "$FINDINGS_TMP" 2>/dev/null)
WARN_COUNT=$(grep -c '^🟡 \*\*WARN\*\*' "$FINDINGS_TMP" 2>/dev/null)
CRITICAL_COUNT=${CRITICAL_COUNT:-0}
WARN_COUNT=${WARN_COUNT:-0}

if [[ -s "$FINDINGS_TMP" ]]; then
    cat "$FINDINGS_TMP" >> "$REPORT"
else
    echo "✅ All checks passed. No findings." >> "$REPORT"
fi
rm -f "$FINDINGS_TMP"

# ============================================================================
# Summary
# ============================================================================
cat >> "$REPORT" <<EOF

---

## Summary

- 🔴 CRITICAL: $CRITICAL_COUNT
- 🟡 WARN: $WARN_COUNT

## Next Action

EOF

if [[ "$CRITICAL_COUNT" -gt 0 ]]; then
    echo "Open a Claude Code session and run \`/audit-config\` for detailed remediation suggestions." >> "$REPORT"
elif [[ "$WARN_COUNT" -gt 0 ]]; then
    echo "Review warnings at your convenience. Non-blocking but worth cleaning up." >> "$REPORT"
else
    echo "Nothing to do. Configuration is clean against known drift patterns." >> "$REPORT"
fi

# Print summary to stdout (visible in launchd log)
echo "Audit complete: $REPORT"
echo "CRITICAL: $CRITICAL_COUNT, WARN: $WARN_COUNT"

# Exit code reflects severity
if [[ "$CRITICAL_COUNT" -gt 0 ]]; then exit 1; fi
exit 0
